### ISSUE TITLE
TypeError: XMLHttpRequest is not a function

### ISSUE THREAD

**Issue by genecyber** [uzyn/web3-loader#11]
No matter how I try I'm unable to use the web3.eth or even the instantiated contract["eth"] in any way that reaches out via XMLHttpRequest

```
Hash: 09f3e4cee5c2c24ee28e
Version: webpack 1.13.0
Time: 6183ms
    Asset    Size  Chunks             Chunk Names
bundle.js  502 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 88 hidden modules
C:\repo\ethereum-webpack-example-dapp\bundle.js:16073
            var request = new XMLHttpRequest();
                          ^

TypeError: XMLHttpRequest is not a function
```

```
import { tokenRecipient, MyToken, web3 } from '.\\MyToken.sol';
let currentBlock = web3.eth.blockNumber;
console.log(currentBlock);
```

**Comment by uzyn** [comment]
@genecyber Do you have the full code or package somewhere where this error can be reproduced?

**Comment by genecyber** [comment]
So I forgot to mention I'm running this outside of a browser.

First I cloned the ethereum-webpack-example-dapp
npm install
npm start

verified that the bundle worked in the browser (It worked)

I then commented out the window bits and re ran npm start

```
/**
 * Individual contracts are available instantiated
 * Also avaialble is initialized web3 object
 */
import { tokenRecipient, MyToken, web3 } from './contract/MyToken.sol';

/*window.onload = () => {
  renderWeb3Details();
  renderTokenDetails();
};

function renderWeb3Details() {
  document.getElementById('provider').innerHTML = web3.currentProvider.host;
  document.getElementById('latest-block').innerHTML = web3.eth.blockNumber;

  const accounts = web3.eth.accounts;
  let html = '';
  for (let account of web3.eth.accounts) {
    html += `${account}<br>\n`;
  }
  document.getElementById('list-accounts').innerHTML = html;
}

function renderTokenDetails() {
  document.getElementById('token-name').innerHTML = MyToken.name();
  document.getElementById('token-symbol').innerHTML = MyToken.symbol();
  document.getElementById('total-supply').innerHTML = MyToken.totalSupply();
  document.getElementById('version').innerHTML = MyToken.version();
}*/
console.log(web3.eth.blockNumber)
console.log(web3);
console.log(MyToken);
console.log(tokenRecipient);
```

I also added

```
console.log(web3.eth.blockNumber)
```

upon successful webpaking I ran node bundle.js and got this error

```
 node bundle.js
C:\repo\ethereum-webpack-example-dapp\bundle.js:16072
            var request = new XMLHttpRequest();
                          ^

TypeError: XMLHttpRequest is not a function
    at HttpProvider.prepareRequest (C:\repo\ethereum-webpack-example-dapp\bundle.js:16072:20)
    at HttpProvider.send (C:\repo\ethereum-webpack-example-dapp\bundle.js:16086:25)
    at RequestManager.send (C:\repo\ethereum-webpack-example-dapp\bundle.js:338:33)
    at Eth.get [as blockNumber] (C:\repo\ethereum-webpack-example-dapp\bundle.js:12252:63)
    at Object.<anonymous> (C:\repo\ethereum-webpack-example-dapp\bundle.js:81:31)
    at __webpack_require__ (C:\repo\ethereum-webpack-example-dapp\bundle.js:20:30)
    at Object.<anonymous> (C:\repo\ethereum-webpack-example-dapp\bundle.js:47:19)
    at __webpack_require__ (C:\repo\ethereum-webpack-example-dapp\bundle.js:20:30)
    at C:\repo\ethereum-webpack-example-dapp\bundle.js:40:18
    at Object.<anonymous> (C:\repo\ethereum-webpack-example-dapp\bundle.js:43:10)
```

Also noteworthy I'm on windows 10

**Comment by uzyn** [comment]
@genecyber You'll have to add `target: 'node'` to webpack.config.js so that the code will run in non-browser mode.

**Comment by genecyber** [comment]
Thanks much that fixed it.

**Comment by blackbutler756** [comment]
I m facing  this error
```
> web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));
undefined
> var coinbase = web3.eth.coinbase;
TypeError: 'XMLHttpRequest' is not a function
    at web3.js:4241:21
    at web3.js:4257:19
    at web3.js:6188:18
    at get (web3.js:6091:38)
    at <unknown>
```
