### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by Legogris** [uzyn/web3-loader#9]
Running https://github.com/uzyn/ethereum-webpack-example-dapp, I get the following:

```
ERROR in ./contract/MyToken.sol
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Module._compile (module.js:536:22)
    at Object.loaderContext.exec (/home/legogris/dev/eth/ethereum-webpack-example-dapp/node_modules/webpack-core/lib/NormalModuleMixin.js:90:7)
    at Object.module.exports (/home/legogris/dev/eth/ethereum-webpack-example-dapp/node_modules/web3-loader/index.js:18:24) @ ./index.js 3:15-48
```

This is fixed by #8.

**Comment by uzyn** [comment]
Thanks @Legogris 

Silly me. I submitted a PR to Webpack to "fix" this issue for Node.js v6. https://github.com/webpack/core/pull/22

Didn't realized I missed a param. Thanks!
